export const homeObjOne = {
id: 'sobrenosotros',
lightBg: false,
lightText: true,
lightTextDesc: true,
topLine: 'La mejor calidad',
headline: 'Al alcance de tu bolsillo',
description: 'Compra a nuestros vendedores locales desde tu casa registrándote en nuestra página o vende tus productos y dáte a conocer.',
imgStart: false,
img: require('../../../../images/Home/svg-1.svg'),
alt: 'img1',
dark: true,
primary: true,
darkText: false,
}
